import re

# ─── FIX 1 & 2 & 3 & 4: style.css patches ───────────────────────────────────
with open('style.css', 'r') as f:
    css = f.read()

# FIX 1: Replace old .tool-item block (opacity:0, scale(0.92)) with a neutral
# placeholder that preserves .tools-grid and .tool-item-name without poisoning
# the new bento grid tool items.
old_tools_block = """.tools-grid {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s-6);
  margin-top: var(--s-12);
  align-items: center;
}
.tool-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--s-3);
  opacity: 0;
  transform: scale(0.92);
}
.tool-item img {
  width: clamp(48px, 8vw, 80px);
  height: clamp(48px, 8vw, 80px);
  object-fit: contain;
  border-radius: var(--radius-md);
  filter: grayscale(30%) brightness(0.9);
  transition: filter 0.3s ease, transform 0.3s ease, drop-shadow 0.3s ease;
}
.tool-item:hover img {
  filter: grayscale(0%) brightness(1.1) drop-shadow(0 0 16px rgba(0, 255, 170, 0.4));
  transform: scale(1.15) translateY(-4px);
}
.tool-item-name {
  font-family: var(--font-mono);
  font-size: var(--text-2xs);
  color: var(--gray-3);
  letter-spacing: var(--track-wide);
  text-transform: uppercase;
  transition: color 0.3s ease;
}
.tool-item:hover .tool-item-name { color: var(--green); }"""

new_tools_block = """.tools-grid {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s-6);
  margin-top: var(--s-12);
  align-items: center;
}
/* Legacy .tool-item base — does NOT set opacity or transform so the
   new bento grid items are not poisoned. The new .tool-item styles
   at the bottom of this file (PREMIUM BENTO TOOL GRID) take over. */
.tool-item-name {
  font-family: var(--font-mono);
  font-size: var(--text-2xs);
  color: var(--gray-3);
  letter-spacing: var(--track-wide);
  text-transform: uppercase;
  transition: color 0.3s ease;
}
.tool-item:hover .tool-item-name { color: var(--green); }"""

if old_tools_block in css:
    css = css.replace(old_tools_block, new_tools_block)
    print("FIX 1: Removed duplicate tool-item opacity:0 block ✓")
else:
    print("FIX 1: Block not found — check manually")

# FIX 2: Change physics-grid from fixed height + overflow:hidden to flexible
old_physics_grid = """.physics-grid {
  position: relative;
  width: 100%;
  height: 240px;
  overflow: hidden;
  border-radius: var(--radius-md);
  /* The canvas will be auto-generated by Matter.js if needed, or we just sync DOM */
}"""

new_physics_grid = """.physics-grid {
  position: relative;
  width: 100%;
  /* Height is now content-driven — no fixed clip */
  border-radius: var(--radius-md);
}"""

if old_physics_grid in css:
    css = css.replace(old_physics_grid, new_physics_grid)
    print("FIX 2: physics-grid fixed height removed ✓")
else:
    print("FIX 2: physics-grid block not found — check manually")

# FIX 3: Upgrade the PREMIUM BENTO TOOL GRID section — better padding,
# smaller min column, remove empty width:100% (redundant in grid child)
old_bento_grid_css = """/* --- PREMIUM BENTO TOOL GRID --- */
.db-tools-container {
    display: grid !important;
    grid-template-columns: repeat(auto-fill, minmax(72px, 1fr));
    gap: 1.25rem;
    width: 100%;
    /* Removed the ugly double-padding and backgrounds */
}"""

new_bento_grid_css = """/* --- PREMIUM BENTO TOOL GRID --- */
.db-tools-container {
    display: grid !important;
    grid-template-columns: repeat(auto-fill, minmax(60px, 1fr));
    gap: 0.875rem;
    padding: 0.5rem 0; /* Breathing room without eating bento padding */
}"""

if old_bento_grid_css in css:
    css = css.replace(old_bento_grid_css, new_bento_grid_css)
    print("FIX 3: db-tools-container minmax and padding updated ✓")
else:
    print("FIX 3: bento grid CSS block not found — check manually")

# FIX 4: Add word-break fix to hero-name mobile override.
# Find the existing mobile hero-name override and update it.
old_hero_mobile = "      .hero-name { font-size: clamp(2.75rem, 14vw, 11rem); }"
new_hero_mobile = """      .hero-name { font-size: clamp(2.75rem, 14vw, 11rem); word-break: break-word; overflow-wrap: break-word; }
      .hero-name-line { white-space: normal; }"""

if old_hero_mobile in css:
    css = css.replace(old_hero_mobile, new_hero_mobile)
    print("FIX 4: Hero name word-break added ✓")
else:
    print("FIX 4: hero-name mobile rule not found — check manually")

with open('style.css', 'w') as f:
    f.write(css)

print("\nAll CSS fixes written to style.css.")
