import re

with open('style.css', 'r') as f:
    css = f.read()

# Replace the tool-specific marquee/radar/float grids with physics-grid
old_css_part1 = """/* Marquee Track inside Dev Box */
.marquee-wrapper {
  overflow: hidden;
  position: relative;
  width: 100%;
  display: flex;
  align-items: center;
  z-index: 2;
  mask-image: linear-gradient(to right, transparent, black 10%, black 90%, transparent);
  -webkit-mask-image: linear-gradient(to right, transparent, black 10%, black 90%, transparent);
}
.marquee-track {
  display: flex;
  gap: var(--s-16);
  width: max-content;
  animation: scroll-left 30s linear infinite;
  padding: var(--s-8) 0;
}
.marquee-wrapper:hover .marquee-track {
  animation-play-state: paused;
}

@keyframes scroll-left {
  from { transform: translateX(0); }
  to { transform: translateX(calc(-50% - var(--s-16)/2)); }
}

/* Sub-grid styles inside Bentos */
.radar-scan {
  flex-wrap: wrap;
  gap: var(--s-6);
  background: radial-gradient(circle, rgba(0,255,170,0.1) 0%, transparent 70%);
  border-radius: 50%;
  padding: var(--s-4);
}
.radar-scan:hover .tool-item img {
  animation: glitch-anim 0.3s ease infinite alternate;
}
@keyframes glitch-anim {
  0% { transform: translate(0, 0); filter: hue-rotate(0deg); }
  100% { transform: translate(-2px, 2px); filter: hue-rotate(90deg); }
}

.float-grid {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s-8);
}
.float-grid .tool-item {
  transition: transform 0.5s cubic-bezier(0.2, 0.8, 0.2, 1);
}
.bento-des:hover .float-grid .tool-item {
  transform: perspective(400px) rotateX(10deg) rotateY(-10deg) translateZ(10px);
}

.nodes-grid {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s-8);
  background-image: radial-gradient(rgba(0, 255, 170, 0.2) 1px, transparent 1px);
  background-size: 20px 20px;
}"""

new_css_part1 = """/* Physics Grid Backgrounds */
.physics-grid {
  position: relative;
  width: 100%;
  height: 240px;
  overflow: hidden;
  border-radius: var(--radius-md);
  /* The canvas will be auto-generated by Matter.js if needed, or we just sync DOM */
}

/* Background flavors */
.bento-sec .physics-grid {
  background: radial-gradient(circle, rgba(0,255,170,0.1) 0%, transparent 70%);
}
.bento-aut .physics-grid {
  background-image: radial-gradient(rgba(0, 255, 170, 0.2) 1px, transparent 1px);
  background-size: 20px 20px;
}

/* Make tool items position absolute for Matter.js sync */
.physics-grid .tool-item {
  position: absolute;
  top: 0;
  left: 0;
  margin: 0;
  cursor: grab;
  /* Matter.js calculates transform, so we remove transition to prevent lag */
  transition: none !important; 
  opacity: 1 !important; /* Force visibility immediately */
}
.physics-grid .tool-item:active {
  cursor: grabbing;
}
.physics-grid .tool-item img {
  pointer-events: none; /* Let the container handle dragging */
}

@keyframes scroll-left {
  from { transform: translateX(0); }
  to { transform: translateX(calc(-50% - var(--s-16)/2)); }
}
"""

if old_css_part1 in css:
    css = css.replace(old_css_part1, new_css_part1)

with open('style.css', 'w') as f:
    f.write(css)
